//USER reducer type
export const VALIDATE_TOKEN = "VALIDATE_TOKEN"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const VERIFY_USER = "VERIFY_USER"
export const REGISTER_USER = "REGISTER_USER"
export const GET_USERS = "GET_USERS"
export const GET_ONE_USER = "GET_ONE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const ADD_USER = "ADD_USER"
export const DELETE_USER = "DELETE_USER"

//UI reducer types
export const SET_ERRORS = "SET_ERRORS"
export const LOADING_UI = "LOADING_UI "
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_DATA = "LOADING_DATA"
export const STOP_LOADING_UI = "STOP_LOADING_UI"