//USER reducer type
export const VALIDATE_TOKEN = "VALIDATE_TOKEN"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const VERIFY_USER = "VERIFY_USER"
export const REGISTER_USER = "REGISTER_USER"
export const GET_USERS = "GET_USERS"
export const GET_ONE_USER = "GET_ONE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const ADD_USER = "ADD_USER"
export const DELETE_USER = "DELETE_USER"
export const ADD_TO_CART_USER ="ADD_TO_CART_USER"
export const GET_CART_ITEMS_USER = "GET_CART_ITEMS_USER"
export const REMOVE_CART_ITEM_USER = "REMOVE_CART_ITEM_USER"
export const ON_SUCCESS_BUY = "ON_SUCCESS_BUY,"
//UI reducer types
